---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: projectbudgets.finops.acasa.acme
spec:
  group: finops.acasa.acme
  names:
    kind: ProjectBudget
    listKind: ProjectBudgetList
    plural: projectbudgets
    singular: projectbudget
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: ProjectBudget is the Schema for the projectbudgets API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: spec defines the desired state of ProjectBudget
            properties:
              maxCpuLimit:
                description: MaxCpuLimit is the maximum total CPU allowed for the
                  namespace (e.g., "2000m" = 2 Cores)
                pattern: ^\d+(m|)$
                type: string
              maxMemoryLimit:
                description: MaxMemoryLimit is the maximum total Memory allowed (e.g.,
                  "4Gi")
                pattern: ^\d+(Mi|Gi)$
                type: string
              teamName:
                description: TeamName is the name of the namespace/label to govern
                  (e.g., "team-alpha")
                minLength: 1
                type: string
              validationMode:
                default: Enforce
                description: |-
                  EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
                  NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.
                enum:
                - Enforce
                - DryRun
                type: string
            required:
            - maxCpuLimit
            - teamName
            type: object
          status:
            description: status defines the observed state of ProjectBudget
            properties:
              currentCpuUsage:
                description: CurrentCpuUsage shows the total CPU requests found in
                  the namespace
                type: string
              lastCheckTime:
                description: LastCheckTime is the timestamp of the last reconciliation
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
